# Generated by Django 3.1.12 on 2024-12-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileU', '0002_auto_20241205_1339'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileupload',
            table='FileU',
        ),
    ]
