# Generated by Django 3.1.12 on 2024-12-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileU', '0004_auto_20241205_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='id',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
